"""empty message

Revision ID: b86c8a3c69d1
Revises: 
Create Date: 2020-03-09 14:37:12.651363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b86c8a3c69d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('course_name', sa.String(length=255), nullable=True),
    sa.Column('chapter_name', sa.String(length=255), nullable=True),
    sa.Column('_image_url', sa.String(length=255), nullable=True),
    sa.Column('course_type_id', sa.SmallInteger(), nullable=True),
    sa.Column('course_type', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('_video_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_type',
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('course_type', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_type')
    op.drop_table('course')
    # ### end Alembic commands ###
