"""empty message

Revision ID: c4ffbc8a4449
Revises: b86c8a3c69d1
Create Date: 2020-03-09 14:39:23.790319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4ffbc8a4449'
down_revision = 'b86c8a3c69d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('course_type', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_type', 'create_time')
    op.drop_column('course', 'create_time')
    # ### end Alembic commands ###
